### PR TITLE
Create LICENSE

### LINKED ISSUE #19: specify license
Please add licensing information to this repository.

### PR DESCRIPTION
**Pull request by Arnei**
Resolves #19

### CODE REVIEW

**Comment by lkiesow** [comment]
In your `post_archive.rb` you are including BBB libraries which are GPL, are they not?
If they are, you should license this as GPL.

**Comment by lkiesow** [comment]
Or maybe LGPL.
The `post_publish.rb` is also already licensed under the LGPL.
Adding a top-level MIT license would be confusing.

**Comment by Rillke** [comment]
I agree to license my contributions under whatever OSI approved open source license you choose.

**Comment by Rillke** [comment]
Can this be merged? (I can't formally approve but I would if I could.)

**Comment by Rillke** [comment]
Maybe squash your changes during merge/rebase. It would be possibly confusing to have a license change in the commit history.

**Pull request merged**
